// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_ce64qjg74nWmbG-oD482ROAOL2j3IE',
    appId: '1:787417913447:web:19ecd281bbc473d6fa5cc2',
    messagingSenderId: '787417913447',
    projectId: 'abc-e-mart-b0e05',
    authDomain: 'abc-e-mart-b0e05.firebaseapp.com',
    storageBucket: 'abc-e-mart-b0e05.firebasestorage.app',
    measurementId: 'G-240BXY6WPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmkD7hFTd5GkQm8YDDEtSssUjTi99Rqk',
    appId: '1:787417913447:android:8fbbc78a96823ceefa5cc2',
    messagingSenderId: '787417913447',
    projectId: 'abc-e-mart-b0e05',
    storageBucket: 'abc-e-mart-b0e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92q3HQutzl0B-4udLFKmqetj6ur2lOew',
    appId: '1:787417913447:ios:1b2276e6efbe5813fa5cc2',
    messagingSenderId: '787417913447',
    projectId: 'abc-e-mart-b0e05',
    storageBucket: 'abc-e-mart-b0e05.firebasestorage.app',
    iosClientId: '787417913447-2bsctdek412kpsvcp7595disptfmsrnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcEMart',
  );
}
