// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVCGTKqCtG9_4pn4STMFDF4rxh-yHtvU',
    appId: '1:251957838828:web:4ae48aca3a0a54532936c9',
    messagingSenderId: '251957838828',
    projectId: 'abc-e-mart-74fde',
    authDomain: 'abc-e-mart-74fde.firebaseapp.com',
    storageBucket: 'abc-e-mart-74fde.firebasestorage.app',
    measurementId: 'G-TFPTWP76J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_WOrrKRtpiuBciXHG2Qqyea8ENU9k2A',
    appId: '1:251957838828:android:cecdd4eae51ba0012936c9',
    messagingSenderId: '251957838828',
    projectId: 'abc-e-mart-74fde',
    storageBucket: 'abc-e-mart-74fde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMj8Gr-ud19Bxlp8eBCh6KWCSzLnjfdx0',
    appId: '1:251957838828:ios:50c58c12aec1e9fc2936c9',
    messagingSenderId: '251957838828',
    projectId: 'abc-e-mart-74fde',
    storageBucket: 'abc-e-mart-74fde.firebasestorage.app',
    iosClientId: '251957838828-o61de0n61unp6qoi0omru8a5m4rkkgsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcEMart',
  );
}
